<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>favicon_bpse.ico</ApplicationIcon>

    <!-- 実行ファイル名を変更 -->
    <AssemblyName>CellCounter</AssemblyName>
  </PropertyGroup>

  <!-- ============================
       Build 時の Python スクリプトコピー（Release）
       ============================ -->
  <Target Name="CopyPythonOnBuild"
          AfterTargets="Build"
          Condition="'$(Configuration)' == 'Release'">

    <Copy SourceFiles="..\CellCounter.Py\server.py"
          DestinationFolder="$(OutDir)" />

    <Copy SourceFiles="..\CellCounter.Py\remove_edge_cells.py"
          DestinationFolder="$(OutDir)" />

    <Copy SourceFiles="..\CellCounter.Py\overlay.py"
          DestinationFolder="$(OutDir)" />

    <Copy SourceFiles="..\CellCounter.Py\get_cellpose_info.py"
          DestinationFolder="$(OutDir)" />
  </Target>

  <!-- ============================
       Publish 時の Python スクリプトコピー（Release）
       ============================ -->
  <Target Name="CopyPythonScripts"
          AfterTargets="Publish"
          Condition="'$(Configuration)' == 'Release'">

    <Copy SourceFiles="..\CellCounter.Py\server.py"
          DestinationFolder="$(PublishDir)" />

    <Copy SourceFiles="..\CellCounter.Py\remove_edge_cells.py"
          DestinationFolder="$(PublishDir)" />

    <Copy SourceFiles="..\CellCounter.Py\overlay.py"
          DestinationFolder="$(PublishDir)" />

    <Copy SourceFiles="..\CellCounter.Py\get_cellpose_info.py"
          DestinationFolder="$(PublishDir)" />
  </Target>

  <!-- ============================
       Clean（Python スクリプト削除）
       ============================ -->
  <Target Name="CleanCopiedPython"
          BeforeTargets="Clean"
          Condition="'$(Configuration)' == 'Release'">

    <Delete Files="$(OutDir)server.py" />
    <Delete Files="$(OutDir)remove_edge_cells.py" />
    <Delete Files="$(OutDir)overlay.py" />
    <Delete Files="$(OutDir)get_cellpose_info.py" />

    <Delete Files="$(PublishDir)server.py" />
    <Delete Files="$(PublishDir)remove_edge_cells.py" />
    <Delete Files="$(PublishDir)overlay.py" />
    <Delete Files="$(PublishDir)get_cellpose_info.py" />
  </Target>

  <!-- アイコン -->
  <ItemGroup>
    <Content Include="favicon_bpse.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
